### ISSUE TITLE
OverflowError when converting `math.inf` to capacity

### ISSUE THREAD

**Issue by ayalash** [vmalloc/capacity#14]
```
>>> capacity.byte * math.inf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ayalas/src/github/capacity/capacity/capacity.py", line 71, in __mul__
    allow_nonzero_ints=True)
  File "/home/ayalas/src/github/capacity/capacity/capacity.py", line 144, in _arithmetic_to_capacity
    return Capacity(self._arithmetic_to_number(*args, **kwargs))
  File "/home/ayalas/src/github/capacity/capacity/capacity.py", line 140, in _arithmetic_to_number
    operand = Capacity(operand)
  File "/home/ayalas/src/github/capacity/capacity/capacity.py", line 22, in __init__
    if isinstance(bits, float) and bits == math.floor(bits):
OverflowError: cannot convert float infinity to integer
```
It worked well started failing in 1.3.9

**Comment by ayalash** [comment]
The overflow raises from the `math` library:
```
>>> math.floor(math.inf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
```
I think that we just need to add "and bits is not math.inf" in line 22 for fixing it.

**Comment by vmalloc** [comment]
Agreed
